name = "AXMethods"
uuid = "1d291744-7f5e-4378-97a1-ef9e31d7fbb4"
authors = ["Ariel Xu <nyxu@uchicago.edu>"]
version = "0.1.0"

[compat]
julia = "1.6.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
